/*
 * Copyright (c) 2026 众汇云创科技（深圳）有限公司.
 * This file is part of ZHYC and is licensed for non-commercial use only.
 * Commercial use requires a separate written license from the copyright holder.
 * SPDX-License-Identifier: LicenseRef-ZHYC-NonCommercial
 */

package com.zhyc.lowcode.db.postgresql;

import com.zhyc.lowcode.db.DdlGenerationSupport;
import com.zhyc.lowcode.db.DdlGenerator;
import com.zhyc.lowcode.db.FieldTypeMapper;
import com.zhyc.lowcode.db.LowcodeColumn;
import com.zhyc.lowcode.db.LowcodeTable;
import com.zhyc.lowcode.metadata.domain.LowcodeDatabaseDialect;
import java.util.List;
import java.util.Objects;

/**
 * PostgreSQL DDL 生成器。
 */
public class PostgreSqlDdlGenerator implements DdlGenerator {

  /** 字段类型映射器。 */
  private final FieldTypeMapper fieldTypeMapper;

  /**
   * 创建 PostgreSQL DDL 生成器。
   *
   * @param fieldTypeMapper 字段类型映射器
   */
  public PostgreSqlDdlGenerator(FieldTypeMapper fieldTypeMapper) {
    this.fieldTypeMapper = Objects.requireNonNull(fieldTypeMapper, "字段类型映射器不能为空");
  }

  /**
   * 返回 PostgreSQL 方言名称。
   *
   * @return postgresql
   */
  @Override
  public String getDialectName() {
    return LowcodeDatabaseDialect.POSTGRESQL.getCode();
  }

  /**
   * 生成 PostgreSQL 创建数据表 DDL。
   *
   * @param table 低代码数据表模型
   * @return PostgreSQL 创建数据表 DDL
   */
  @Override
  public String generateCreateTable(LowcodeTable table) {
    List<LowcodeColumn> columns = table.getColumns();
    StringBuilder ddl = new StringBuilder();
    ddl.append("CREATE TABLE IF NOT EXISTS ")
        .append(quote(table.getName()))
        .append(" (\n");
    for (int i = 0; i < columns.size(); i++) {
      ddl.append("    ").append(columnDefinition(columns.get(i))).append(",\n");
    }
    ddl.append("    PRIMARY KEY (")
        .append(DdlGenerationSupport.primaryKeys(columns, PostgreSqlDdlGenerator::quote))
        .append(")\n);");
    appendComments(ddl, table, columns);
    appendTenantDeletedIndex(ddl, table, columns);
    return ddl.toString();
  }

  private String columnDefinition(LowcodeColumn column) {
    StringBuilder definition = new StringBuilder();
    definition.append(quote(column.getName()))
        .append(" ")
        .append(fieldTypeMapper.toDatabaseType(column));
    if (column.isAutoIncrement()) {
      definition.append(" GENERATED BY DEFAULT AS IDENTITY");
    }
    definition.append(column.isNullable() ? " NULL" : " NOT NULL");
    String defaultClause = commonColumnDefaultClause(column);
    if (DdlGenerationSupport.hasText(defaultClause)) {
      definition.append(" ").append(defaultClause);
    }
    return definition.toString();
  }

  private static void appendComments(StringBuilder ddl, LowcodeTable table, List<LowcodeColumn> columns) {
    if (DdlGenerationSupport.hasText(table.getComment())) {
      ddl.append("\nCOMMENT ON TABLE ")
          .append(quote(table.getName()))
          .append(" IS '")
          .append(DdlGenerationSupport.escapeComment(table.getComment()))
          .append("';");
    }
    for (LowcodeColumn column : columns) {
      if (DdlGenerationSupport.hasText(column.getComment())) {
        ddl.append("\nCOMMENT ON COLUMN ")
            .append(quote(table.getName()))
            .append(".")
            .append(quote(column.getName()))
            .append(" IS '")
            .append(DdlGenerationSupport.escapeComment(column.getComment()))
            .append("';");
      }
    }
  }

  private static void appendTenantDeletedIndex(StringBuilder ddl, LowcodeTable table, List<LowcodeColumn> columns) {
    if (!DdlGenerationSupport.needsTenantDeletedIndex(columns)) {
      return;
    }
    ddl.append("\nCREATE INDEX IF NOT EXISTS ")
        .append(quote(DdlGenerationSupport.tenantDeletedIndexName(table.getName())))
        .append(" ON ")
        .append(quote(table.getName()))
        .append(" (")
        .append(quote("tenant_id"))
        .append(", ")
        .append(quote("deleted"))
        .append(");");
  }

  private static String commonColumnDefaultClause(LowcodeColumn column) {
    return switch (column.getName().toLowerCase()) {
      case "created_at", "updated_at" -> "DEFAULT CURRENT_TIMESTAMP";
      case "deleted" -> "DEFAULT FALSE";
      case "version" -> "DEFAULT 0";
      default -> "";
    };
  }

  private static String quote(String identifier) {
    return "\"" + DdlGenerationSupport.requireIdentifier(identifier) + "\"";
  }
}
