/*
 * Copyright (c) 2026 众汇云创科技（深圳）有限公司.
 * This file is part of ZHYC and is licensed for non-commercial use only.
 * Commercial use requires a separate written license from the copyright holder.
 * SPDX-License-Identifier: LicenseRef-ZHYC-NonCommercial
 */

package com.zhyc.lowcode.db;

import com.zhyc.lowcode.db.mysql.MySqlDdlGenerator;
import com.zhyc.lowcode.db.mysql.MySqlFieldTypeMapper;
import com.zhyc.lowcode.db.mysql.MySqlPaginationDialect;
import com.zhyc.lowcode.db.dm.DmDdlGenerator;
import com.zhyc.lowcode.db.dm.DmFieldTypeMapper;
import com.zhyc.lowcode.db.dm.DmPaginationDialect;
import com.zhyc.lowcode.db.oracle.OracleDdlGenerator;
import com.zhyc.lowcode.db.oracle.OracleFieldTypeMapper;
import com.zhyc.lowcode.db.oracle.OraclePaginationDialect;
import com.zhyc.lowcode.db.postgresql.PostgreSqlDdlGenerator;
import com.zhyc.lowcode.db.postgresql.PostgreSqlFieldTypeMapper;
import com.zhyc.lowcode.db.postgresql.PostgreSqlPaginationDialect;
import com.zhyc.lowcode.db.sqlserver.SqlServerDdlGenerator;
import com.zhyc.lowcode.db.sqlserver.SqlServerFieldTypeMapper;
import com.zhyc.lowcode.db.sqlserver.SqlServerPaginationDialect;
import java.util.List;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 主流数据库低代码方言兼容测试。
 */
class MultiDatabaseDialectTest {

  /**
   * 验证主流数据库字段类型映射结果稳定，避免生成 DDL 时混用 MySQL 类型。
   */
  @Test
  void shouldMapFieldTypesForMainstreamDatabases() {
    LowcodeDbDialectService service = createMultiDatabaseService();
    LowcodeColumn name = LowcodeColumn.builder("name", LowcodeFieldType.STRING).length(64).build();
    LowcodeColumn amount = LowcodeColumn.builder("amount", LowcodeFieldType.DECIMAL).length(18).scale(2).build();
    LowcodeColumn enabled = LowcodeColumn.builder("enabled", LowcodeFieldType.BOOLEAN).build();

    assertEquals("VARCHAR(64)", service.mapFieldType("postgresql", name));
    assertEquals("NUMERIC(18,2)", service.mapFieldType("postgresql", amount));
    assertEquals("BOOLEAN", service.mapFieldType("postgresql", enabled));
    assertEquals("VARCHAR2(64)", service.mapFieldType("oracle", name));
    assertEquals("NUMBER(18,2)", service.mapFieldType("oracle", amount));
    assertEquals("NUMBER(1)", service.mapFieldType("oracle", enabled));
    assertEquals("NVARCHAR(64)", service.mapFieldType("sqlserver", name));
    assertEquals("DECIMAL(18,2)", service.mapFieldType("sqlserver", amount));
    assertEquals("BIT", service.mapFieldType("sqlserver", enabled));
    assertEquals("VARCHAR(64)", service.mapFieldType("dm", name));
    assertEquals("NUMBER(18,2)", service.mapFieldType("dm", amount));
    assertEquals("NUMBER(1)", service.mapFieldType("dm", enabled));
  }

  /**
   * 验证主流数据库分页语法按方言输出，避免 SQL Server、Oracle 误用 MySQL LIMIT。
   */
  @Test
  void shouldApplyPaginationForMainstreamDatabases() {
    LowcodeDbDialectService service = createMultiDatabaseService();

    assertEquals("SELECT id FROM demo LIMIT 10 OFFSET 20",
        service.applyPagination("postgresql", "SELECT id FROM demo", 20, 10));
    assertEquals("SELECT id FROM demo OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
        service.applyPagination("oracle", "SELECT id FROM demo", 20, 10));
    assertEquals("SELECT id FROM demo ORDER BY (SELECT NULL) OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
        service.applyPagination("sqlserver", "SELECT id FROM demo", 20, 10));
    assertEquals("SELECT id FROM demo OFFSET 20 ROWS FETCH NEXT 10 ROWS ONLY",
        service.applyPagination("dm", "SELECT id FROM demo", 20, 10));
  }

  /**
   * 验证 DDL 生成器按数据库输出标识符、自增和注释语法。
   */
  @Test
  void shouldGenerateCreateTableDdlForMainstreamDatabases() {
    LowcodeDbDialectService service = createMultiDatabaseService();
    LowcodeTable table = demoTable();

    String postgresql = service.generateCreateTable("postgresql", table);
    assertTrue(postgresql.contains("\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
    assertTrue(postgresql.contains("COMMENT ON TABLE \"biz_user\" IS '用户表';"));
    assertTrue(postgresql.contains("CREATE INDEX IF NOT EXISTS \"idx_biz_user_tenant_deleted\""));

    String oracle = service.generateCreateTable("oracle", table);
    assertTrue(oracle.contains("\"id\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
    assertTrue(oracle.contains("COMMENT ON TABLE \"biz_user\" IS '用户表'"));
    assertTrue(oracle.contains("CREATE INDEX \"idx_biz_user_tenant_deleted\""));

    String sqlServer = service.generateCreateTable("sqlserver", table);
    assertTrue(sqlServer.contains("[id] BIGINT IDENTITY(1,1) NOT NULL"));
    assertTrue(sqlServer.contains("EXEC sp_addextendedproperty N'MS_Description', N'用户表'"));
    assertTrue(sqlServer.contains("CREATE INDEX [idx_biz_user_tenant_deleted]"));

    String dm = service.generateCreateTable("dm", table);
    assertTrue(dm.contains("\"id\" BIGINT IDENTITY(1,1) NOT NULL"));
    assertTrue(dm.contains("COMMENT ON TABLE \"biz_user\" IS '用户表'"));
    assertTrue(dm.contains("CREATE INDEX \"idx_biz_user_tenant_deleted\""));
  }

  /**
   * 验证方言能力清单可一次性暴露给后台页面和生成器。
   */
  @Test
  void shouldListMainstreamDialectCapabilities() {
    LowcodeDbDialectService service = createMultiDatabaseService();

    assertEquals(List.of("mysql", "postgresql", "oracle", "sqlserver", "dm"), service.listDdlDialectCodes());
    assertEquals(List.of("mysql", "postgresql", "oracle", "sqlserver", "dm"), service.listFieldTypeDialectCodes());
    assertEquals(List.of("mysql", "postgresql", "oracle", "sqlserver", "dm"), service.listPaginationDialectCodes());
  }

  private static LowcodeTable demoTable() {
    return new LowcodeTable(
        "biz_user",
        "用户表",
        List.of(
            LowcodeColumn.builder("id", LowcodeFieldType.LONG)
                .primaryKey(true)
                .autoIncrement(true)
                .nullable(false)
                .comment("主键")
                .build(),
            LowcodeColumn.builder("tenant_id", LowcodeFieldType.STRING)
                .length(64)
                .nullable(false)
                .comment("租户业务编码")
                .build(),
            LowcodeColumn.builder("deleted", LowcodeFieldType.BOOLEAN)
                .nullable(false)
                .comment("逻辑删除标识")
                .build()));
  }

  private static LowcodeDbDialectService createMultiDatabaseService() {
    MySqlFieldTypeMapper mySqlFieldTypeMapper = new MySqlFieldTypeMapper();
    PostgreSqlFieldTypeMapper postgreSqlFieldTypeMapper = new PostgreSqlFieldTypeMapper();
    OracleFieldTypeMapper oracleFieldTypeMapper = new OracleFieldTypeMapper();
    SqlServerFieldTypeMapper sqlServerFieldTypeMapper = new SqlServerFieldTypeMapper();
    DmFieldTypeMapper dmFieldTypeMapper = new DmFieldTypeMapper();
    LowcodeDbDialectRegistry registry = new LowcodeDbDialectRegistry(
        List.of(
            new MySqlDdlGenerator(mySqlFieldTypeMapper),
            new PostgreSqlDdlGenerator(postgreSqlFieldTypeMapper),
            new OracleDdlGenerator(oracleFieldTypeMapper),
            new SqlServerDdlGenerator(sqlServerFieldTypeMapper),
            new DmDdlGenerator(dmFieldTypeMapper)),
        List.of(mySqlFieldTypeMapper, postgreSqlFieldTypeMapper, oracleFieldTypeMapper, sqlServerFieldTypeMapper,
            dmFieldTypeMapper),
        List.of(
            new MySqlPaginationDialect(),
            new PostgreSqlPaginationDialect(),
            new OraclePaginationDialect(),
            new SqlServerPaginationDialect(),
            new DmPaginationDialect()));
    return new DefaultLowcodeDbDialectService(registry);
  }
}
